url-config:
  SYS_URL: http://localhost:20000
  INFO_URL: http://localhost:20100
  RFS_URL: http://localhost:20300
  UTILS_URL: http://localhost:20400



server:
  port: 20400
spring:
  application:
    name: cloudsys
  datasource:
    url:  jdbc:mysql://localhost:3306/cloud?characterEncoding=utf-8&allowMultiQueries=true&tinyIntlisBit=false # 数据库名称
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver